# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Configuration des services de paiement
    App\Service\Payment\FedaPayService:
        lazy: true
        arguments:
            $publicKey: '%env(FEDAPAY_PUBLIC_KEY)%'
            $privateKey: '%env(FEDAPAY_SECRET_KEY)%'
            $webhookSecret: '%env(FEDAPAY_WEBHOOK_SECRET)%'

    App\Service\Payment\KkiaPayService:
        lazy: true
        arguments:
            $publicKey: '%env(KKIAPAY_PUBLIC_KEY)%'
            $privateKey: '%env(KKIAPAY_PRIVATE_KEY)%'
            $secretKey: '%env(KKIAPAY_SECRET_KEY)%'
            $logger: '@logger'
            $sandbox: '%env(bool:KKIAPAY_SANDBOX)%'

    App\Service\Payment\PayPalService:
        lazy: true
        arguments:
            $clientId: '%env(PAYPAL_CLIENT_ID)%'
            $clientSecret: '%env(PAYPAL_CLIENT_SECRET)%'
            $environment: '%env(PAYPAL_ENVIRONMENT)%'
