# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.contact_email: '%env(CONTACT_EMAIL)%'
    app.noreply_email: '%env(MAIL_FROM_ADDRESS)%'
    app.support_email: '%app.contact_email%'
    app.admin_email: 'rodriguenagnon@gmail.com'
    uploads_directory: '%kernel.project_dir%/var/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'


    # File uploader service
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%uploads_directory%'
            $slugger: '@Symfony\Component\String\Slugger\SluggerInterface'

    # Configuration du service d'email
    App\Service\EmailService:
        arguments:
            $contactEmail: '%app.contact_email%'
            $noreplyEmail: '%app.noreply_email%'
            $projectDir: '%kernel.project_dir%'

    App\Controller\ContactController:
        arguments:
            $contactEmail: '%app.contact_email%'
            $emailService: '@App\Service\EmailService'

    App\Controller\RegistrationController:
        arguments:
            $contactEmail: '%app.contact_email%'

    App\Controller\VerifyEmailController:
        arguments:
            $contactEmail: '%app.contact_email%'

    App\Controller\Admin\SettingAdminController:
        arguments:
            $contactEmail: '%app.contact_email%'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Twig Extension
    App\Twig\AppExtension:
        tags: ['twig.extension']
        arguments:
            $tontineRepository: '@App\Repository\TontineRepository'
            $requestStack: '@request_stack'
            $security: '@security.helper'

    # Configuration de l'écouteur d'événements de connexion
    App\EventListener\LoginListener:
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: 'onSecurityInteractiveLogin' }


    App\Service\Payment\KkiaPayService:
        lazy: true
        arguments:
            $publicKey: '%env(KKIAPAY_PUBLIC_KEY)%'
            $privateKey: '%env(KKIAPAY_PRIVATE_KEY)%'
            $secretKey: '%env(KKIAPAY_SECRET_KEY)%'
            $logger: '@logger'
            $sandbox: '%env(bool:KKIAPAY_SANDBOX)%'

    # Configuration du gestionnaire de consentement aux cookies
    App\Service\CookieConsentManager:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $cookieConsentRepository: '@App\Repository\CookieConsentRepository'
            $requestStack: '@request_stack'

    # Configuration du listener pour les accès refusés
    App\EventListener\AccessDeniedListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

    # Configuration du listener pour le mode maintenance
    App\EventListener\MaintenanceListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 10 }

    # Restriction d'accès pour les comptes en attente de suppression
    App\EventListener\PendingDeletionListener:
        tags:
            - { name: 'kernel.event_subscriber' }